; ASM source file created by SevenuP v1.20
; SevenuP (C) Copyright 2002-2006 by Jaime Tejedor Gomez, aka Metalbrain

;GRAPHIC DATA:
;Pixel Size:      ( 16,   8)
;Char Size:       (  2,   1)
;Sort Priorities: X char, Char line
;Data Outputted:  Gfx+Attr
;Interleave:      Sprite
;Mask:            No

wrld_door_leftup:
	DEFB	 60,199, 66,252,129, 71,133, 64
	DEFB	141, 94,153, 76, 66,128, 60,234
	DEFB	 56, 56