; ASM source file created by SevenuP v1.20
; SevenuP (C) Copyright 2002-2006 by Jaime Tejedor Gomez, aka Metalbrain

;GRAPHIC DATA:
;Pixel Size:      ( 16,  16)
;Char Size:       (  2,   2)
;Sort Priorities: X char, Char line, Y char
;Data Outputted:  Gfx+Attr
;Interleave:      Sprite
;Mask:            No

wrld_door_right:
	DEFB	252,126,  6, 24,242,124,242,132
	DEFB	 50,179, 50,153,242,137, 50,161
	DEFB	252,157, 50,129, 50,145,252,137
	DEFB	 50,153,254, 65, 50,162,254,177
	DEFB	 56, 56, 56, 56