; ASM source file created by SevenuP v1.20
; SevenuP (C) Copyright 2002-2006 by Jaime Tejedor Gomez, aka Metalbrain

;GRAPHIC DATA:
;Pixel Size:      ( 16,  16)
;Char Size:       (  2,   2)
;Sort Priorities: X char, Char line, Y char
;Data Outputted:  Gfx+Attr
;Interleave:      Sprite
;Mask:            No

wrld_door_left:
	DEFB	126, 63, 24, 96, 62, 79, 69, 79
	DEFB	131, 76,185, 76,169, 79,129, 76
	DEFB	 81, 63,138, 76,146, 76,177, 63
	DEFB	129, 76,153,127,145, 76, 81,127
	DEFB	 56, 56, 56, 56