; ASM source file created by SevenuP v1.20
; SevenuP (C) Copyright 2002-2006 by Jaime Tejedor Gomez, aka Metalbrain

;GRAPHIC DATA:
;Pixel Size:      ( 16,  16)
;Char Size:       (  2,   2)
;Sort Priorities: X char, Char line, Y char
;Data Outputted:  Gfx+Attr
;Interleave:      Sprite
;Mask:            No

ply_upA:
	DEFB	  7,224, 15,240, 47,244, 47,244
	DEFB	 63,252, 63,252, 23,232, 25,144
	DEFB	 28, 60, 55,238,127,254,119,238
	DEFB	124, 62, 63,254, 14, 96,  0,112
	DEFB	 60, 60, 60, 60