; ASM source file created by SevenuP v1.20
; SevenuP (C) Copyright 2002-2006 by Jaime Tejedor Gomez, aka Metalbrain

;GRAPHIC DATA:
;Pixel Size:      ( 16,  16)
;Char Size:       (  2,   2)
;Sort Priorities: X char, Char line, Y char
;Data Outputted:  Gfx+Attr
;Interleave:      Sprite
;Mask:            No

wrb_wall:
	DEFB	127,250,191,253,127,254,191,255
	DEFB	255,190,255,213,255,255,235,255
	DEFB	245,255,250,255,253,255,254,255
	DEFB	255,255,255,119,254, 59,117, 82
	DEFB	 56, 56, 56, 56